/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Request to update data in a table in a Word DOCX Document
type DocxTableTableFillMultiRequest struct {
	// Optional; Input URL of the document; use BeginEditing to create this
	InputFileUrl string `json:"InputFileUrl,omitempty"`
	// Optional; Input Word Document file content for the operation
	InputFileData string `json:"InputFileData,omitempty"`
	// Tables and datasets to fill into the document
	TablesToFill []DocxTableSingleTableFill `json:"TablesToFill,omitempty"`
}
