/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Representation of a file in a zip file
type ZipFile struct {
	// Name of this file
	FileName string `json:"FileName,omitempty"`
	// Contents of this file
	FileContents string `json:"FileContents,omitempty"`
}
