/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Input to a Create Blank Word Document request
type CreateBlankDocxRequest struct {
	// Optional; initial text to include in the document
	InitialText string `json:"InitialText,omitempty"`
}
