/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

type VatLookupResponse struct {
	// Two-letter country code
	CountryCode string `json:"CountryCode,omitempty"`
	// VAT number
	VatNumber string `json:"VatNumber,omitempty"`
	// True if the VAT code is valid, false otherwise
	IsValid bool `json:"IsValid,omitempty"`
	// Name of the business
	BusinessName string `json:"BusinessName,omitempty"`
	// Business address as a single string
	BusinessAddress string `json:"BusinessAddress,omitempty"`
	// For the business address, the name of the building, house or structure if applicable, such as \"Cloudmersive Building 2\".  This will often by null.
	BusinessBuilding string `json:"BusinessBuilding,omitempty"`
	// For the business address, the street number or house number of the address.  For example, in the address \"1600 Pennsylvania Avenue NW\" the street number would be \"1600\".  This value will typically be populated for most addresses.
	BusinessStreetNumber string `json:"BusinessStreetNumber,omitempty"`
	// For the business address, the name of the street or road of the address.  For example, in the address \"1600 Pennsylvania Avenue NW\" the street number would be \"Pennsylvania Avenue NW\".
	BusinessStreet string `json:"BusinessStreet,omitempty"`
	// For the business address, the city of the address.
	BusinessCity string `json:"BusinessCity,omitempty"`
	// For the business address, the state or province of the address.
	BusinessStateOrProvince string `json:"BusinessStateOrProvince,omitempty"`
	// For the business address, the postal code or zip code of the address.
	BusinessPostalCode string `json:"BusinessPostalCode,omitempty"`
	// For the business address, country of the address, if present in the address.  If not included in the address it will be null.
	BusinessCountry string `json:"BusinessCountry,omitempty"`
}
