/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Header of a Word Document (DOCX)
type DocxHeader struct {
	// The Path of the location of this object; leave blank for new tables
	Path string `json:"Path,omitempty"`
	// Paragraphs in this header
	Paragraphs []DocxParagraph `json:"Paragraphs,omitempty"`
	// Sections that the header is applied to
	SectionsWithHeader []DocxSection `json:"SectionsWithHeader,omitempty"`
}
