/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Result of running the HTML to Text operation
type HtmlToTextResponse struct {
	// True if successful, false otherwise
	Successful bool `json:"Successful,omitempty"`
	// Text content result from the HTML input
	TextContentResult string `json:"TextContentResult,omitempty"`
}
