/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Request to encrypt an existing Zip Archive file and protect it with a password
type ZipEncryptionAdvancedRequest struct {
	// Input Zip File archive contents in bytes
	InputFileContents string `json:"InputFileContents,omitempty"`
	// Password to place on the Zip file; the longer the password, the more secure
	Password string `json:"Password,omitempty"`
	// Encryption algorithm to use; possible values are AES-256 (recommended), AES-128, and PK-Zip (not recommended; legacy, weak encryption algorithm).  Default is AES-256.
	EncryptionAlgorithm string `json:"EncryptionAlgorithm,omitempty"`
}
