/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Result of performing a zip extract operation
type ZipExtractResponse struct {
	// True if the operation was successful, false otherwise
	Successful bool `json:"Successful,omitempty"`
	// Top-level files in the root directory fo the zip file
	FilesInZip []ZipFile `json:"FilesInZip,omitempty"`
	// Top-level directories in the root directory of the zip; directories can contain sub-directories and files
	DirectoriesInZip []ZipDirectory `json:"DirectoriesInZip,omitempty"`
}
