/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveDocumentConvertApiClient

// User-Agent parse and validation request
type UserAgentValidateRequest struct {
	// The user agent string you wish to parse and validate
	UserAgentString string `json:"UserAgentString,omitempty"`
}
