/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// One page in a Word Document DOCX
type DocxPage struct {
	// Page number of this page, 1-based
	PageNumber int32 `json:"PageNumber,omitempty"`
	// All paragraphs anywhere in the document; these objects are not sequentially placed but are scatted across document
	Paragraphs []DocxParagraph `json:"Paragraphs,omitempty"`
}
