/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// A cell in a Word Document (DOCX) file
type DocxTableCell struct {
	// The index of the cell, 0-based
	CellIndex int32 `json:"CellIndex,omitempty"`
	// The Path of the location of this object; leave blank for new tables
	Path string `json:"Path,omitempty"`
	// Paragraphs inside the cell; this is where the contents of the cell are stored
	Paragraphs []DocxParagraph `json:"Paragraphs,omitempty"`
	// Color of the cell shading
	CellShadingColor string `json:"CellShadingColor,omitempty"`
	// Fill of the cell shading
	CellShadingFill string `json:"CellShadingFill,omitempty"`
	// Pattern of the cell shading
	CellShadingPattern string `json:"CellShadingPattern,omitempty"`
	// Width mode of the cell; can be auto (for automatic) or manual
	CellWidthMode string `json:"CellWidthMode,omitempty"`
	// Width of the cell
	CellWidth string `json:"CellWidth,omitempty"`
}
