/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Result of running a DocxGetFormFields command
type GetDocxGetFormFieldsResponse struct {
	// True if successful, false otherwise
	Successful bool `json:"Successful,omitempty"`
	// Content controls in the DOCX
	ContentControls []DocxContentControl `json:"ContentControls,omitempty"`
	// Form fields that comply with the Handlebar style, that is they are surrounded by two curly braces on either side such as \"{{FieldName}}\", in the DOCX
	HandlebarFormFields []HandlebarFormField `json:"HandlebarFormFields,omitempty"`
}
