/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

type DocxImage struct {
	// The Path of the location of this object; leave blank for new tables
	Path string `json:"Path,omitempty"`
	// The Name of the image
	ImageName string `json:"ImageName,omitempty"`
	// The Id of the image
	ImageId int64 `json:"ImageId,omitempty"`
	// The Description of the image
	ImageDescription string `json:"ImageDescription,omitempty"`
	// Width of the image in EMUs (English Metric Units); set to 0 to default to page width and aspect-ratio based height
	ImageWidth int64 `json:"ImageWidth,omitempty"`
	// Height of the image in EMUs (English Metric Units); set to 0 to default to page width and aspect-ratio based height
	ImageHeight int64 `json:"ImageHeight,omitempty"`
	// X (horizontal) offset of the image
	XOffset int64 `json:"XOffset,omitempty"`
	// Y (vertical) offset of the image
	YOffset int64 `json:"YOffset,omitempty"`
	// Read-only; internal ID for the image contents
	ImageDataEmbedId string `json:"ImageDataEmbedId,omitempty"`
	// Read-only; image data MIME content-type
	ImageDataContentType string `json:"ImageDataContentType,omitempty"`
	// Read-only; internal file name/path for the image
	ImageInternalFileName string `json:"ImageInternalFileName,omitempty"`
	// URL to the image contents; file is stored in an in-memory cache and will be deleted.  Call Finish-Editing to get the contents.
	ImageContentsURL string `json:"ImageContentsURL,omitempty"`
	// True if the image is inline with the text; false if it is floating
	InlineWithText bool `json:"InlineWithText,omitempty"`
}
