/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// HTML template application request
type HtmlTemplateApplicationRequest struct {
	// HTML template input as a string
	HtmlTemplate string `json:"HtmlTemplate,omitempty"`
	// URL to HTML template input
	HtmlTemplateUrl string `json:"HtmlTemplateUrl,omitempty"`
	// Operations to apply to this template
	Operations []HtmlTemplateOperation `json:"Operations,omitempty"`
}
