/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Object representing one document
type DocumentItem struct {
	// File name of the document
	DocumentFileName string `json:"DocumentFileName,omitempty"`
	// Contents of the document as a binary byte array
	DocumentContent string `json:"DocumentContent,omitempty"`
}
