/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// A row in a Word Document (DOCX) file
type DocxTableRow struct {
	// Index of the row, 0-based
	RowIndex int32 `json:"RowIndex,omitempty"`
	// The Path of the location of this table row object; leave blank for new tables
	Path string `json:"Path,omitempty"`
	// Cells in the row; this is where the contents of the row is stored
	RowCells []DocxTableCell `json:"RowCells,omitempty"`
}
