/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Representation of a directory in a zip file
type ZipDirectory struct {
	// Name of this directory
	DirectoryName string `json:"DirectoryName,omitempty"`
	// Child directories contained directly in this directory
	DirectoriesInDirectory []ZipDirectory `json:"DirectoriesInDirectory,omitempty"`
	// Child files contained directly in this directory
	FilesInDirectory []ZipFile `json:"FilesInDirectory,omitempty"`
}
