/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Input to set-footer command
type DocxInsertImageRequest struct {
	// Optional: Bytes of the input file to operate on
	InputDocumentFileBytes string `json:"InputDocumentFileBytes,omitempty"`
	// Optional: URL of a file to operate on as input.  This can be a public URL, or you can also use the begin-editing API to upload a document and pass in the secure URL result from that operation as the URL here (this URL is not public).
	InputDocumentFileUrl string `json:"InputDocumentFileUrl,omitempty"`
	// Optional: Bytes of the input image file to operate on; if you supply this value do not supply InputImageFileUrl or ImageToAdd.
	InputImageFileBytes string `json:"InputImageFileBytes,omitempty"`
	// Optional: URL of an image file to operate on as input; if you supply this value do not supply InputImageFileBytes or ImageToAdd.  This can be a public URL, or you can also use the begin-editing API to upload a document and pass in the secure URL result from that operation as the URL here (this URL is not public).
	InputImageFileUrl string `json:"InputImageFileUrl,omitempty"`
	// Optional: Image to add; if you supply in this object, do not supply InputImageFileBytes or InputImageFileUrl.
	ImageToAdd *DocxImage `json:"ImageToAdd,omitempty"`
	// Optional; default is DocumentEnd.  Placement Type of the insert; possible values are: DocumentStart (very beginning of the document), DocumentEnd (very end of the document), BeforeExistingObject (right before an existing object - fill in the InsertPath field using the Path value from an existing object), AfterExistingObject (right after an existing object - fill in the InsertPath field using the Path value from an existing object)
	InsertPlacement string `json:"InsertPlacement,omitempty"`
	// Optional; location within the document to insert the object; fill in the InsertPath field using the Path value from an existing object.  Used with InsertPlacement of BeforeExistingObject or AfterExistingObject
	InsertPath string `json:"InsertPath,omitempty"`
	// Optional: The width of the image in EMUs
	WidthInEMUs int64 `json:"WidthInEMUs,omitempty"`
	// Optional: The height of the image in EMUs
	HeightInEMUs int64 `json:"HeightInEMUs,omitempty"`
}
