/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Details of the HTML to Text request
type HtmlToTextRequest struct {
	// HTML to extract the text from
	Html string `json:"Html,omitempty"`
}
