/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Result of finding a string
type FindStringRegexResponse struct {
	// True if successful, false otherwise
	Successful bool `json:"Successful,omitempty"`
	// Regular expression matches
	Matches []FindRegexMatch `json:"Matches,omitempty"`
	// The number of matches
	MatchCount int32 `json:"MatchCount,omitempty"`
}
