/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Result of converting a single document page to a PNG thumbnail
type Thumbnail struct {
	// Index of this thumbnail
	Index int32 `json:"Index,omitempty"`
	// A PNG thumbnail of the document page
	Content string `json:"Content,omitempty"`
}
