/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveDocumentConvertApiClient

// Result of a first name validation operation
type FirstNameValidationResponse struct {
	// True if the validation operation was successful, false otherwise
	Successful bool `json:"Successful,omitempty"`
	// Possible values are: ValidFirstName, ValidUnknownFirstName, InvalidSpamInput, InvalidCharacters, InvalidEmpty
	ValidationResult string `json:"ValidationResult,omitempty"`
}
