/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Result of running a Get-Sections command
type GetDocxSectionsResponse struct {
	// True if successful, false otherwise
	Successful bool `json:"Successful,omitempty"`
	// Sections in the DOCX document
	Sections []DocxSection `json:"Sections,omitempty"`
}
