/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveDocumentConvertApiClient

// Result of a partial email address validation
type AddressGetServersResponse struct {
	// True if partial address validation was successufl, false otherwise
	Success bool `json:"Success,omitempty"`
	// Email servers for this email address
	Servers []string `json:"Servers,omitempty"`
}
