/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Result of base 64 decoding
type DetectLineEndingsResponse struct {
	// True if successful, false otherwise
	Successful bool `json:"Successful,omitempty"`
	// Type of newline in the file; possible vlaues are \"Mac\" (legacy Mac OS uses carriage return only); \"Unix\" (Unix and Linux OSes, and modern Mac OS); \"Windows\" (Windows operating systems)
	PrimaryNewlineType string `json:"PrimaryNewlineType,omitempty"`
	// Characters used to terminate a newline; can be carriage return, linefeed, or carriage return + linefeed
	PrimaryNewlineTerminator string `json:"PrimaryNewlineTerminator,omitempty"`
	// Length of the input string in characters
	InputLength int32 `json:"InputLength,omitempty"`
}
