/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Request to decode content from Base 64 into binary
type Base64DecodeRequest struct {
	// Input content to decode from Base 64 into binary
	Base64ContentToDecode string `json:"Base64ContentToDecode,omitempty"`
}
