/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// A single PDF file corresponding to one page in the original document
type PdfDocument struct {
	// Page number of the converted page, starting with 1 for the first page
	PageNumber int32 `json:"PageNumber,omitempty"`
	// URL to the PDF file of this worksheet; file is stored in an in-memory cache and will be deleted
	URL string `json:"URL,omitempty"`
	// If returnDocumentContents is set to true, will contain the contents of the document; otherwise will be set to null and the document contents will be available via the URL parameter
	DocumentContents string `json:"DocumentContents,omitempty"`
}
