/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Input to a Set Cell by identifier in XLSX Worksheets request
type SetXlsxCellByIdentifierRequest struct {
	// Optional: Bytes of the input file to operate on
	InputFileBytes string `json:"InputFileBytes,omitempty"`
	// Optional: URL of a file to operate on as input.  This can be a public URL, or you can also use the begin-editing API to upload a document and pass in the secure URL result from that operation as the URL here (this URL is not public).
	InputFileUrl string `json:"InputFileUrl,omitempty"`
	// Optional; Worksheet (tab) within the spreadsheet to update; leave blank to default to the first worksheet
	WorksheetToUpdate *XlsxWorksheet `json:"WorksheetToUpdate,omitempty"`
	// The Excel cell identifier (e.g. A1, B2, C33, etc.) of the cell to update
	CellIdentifier string `json:"CellIdentifier,omitempty"`
	// New Cell value to update/overwrite into the Excel XLSX spreadsheet
	CellValue *XlsxSpreadsheetCell `json:"CellValue,omitempty"`
}
