/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// A paragraph in a Word Document (DOCX) file; there is where text, content and formatting are stored - similar to the paragraph tag in HTML
type DocxParagraph struct {
	// The index of the paragraph; 0-based
	ParagraphIndex int32 `json:"ParagraphIndex,omitempty"`
	// The Path of the location of this Paragraph object; leave blank during creation
	Path string `json:"Path,omitempty"`
	// The content runs in the paragraph - this is where text is stored; similar to a span in HTML
	ContentRuns []DocxRun `json:"ContentRuns,omitempty"`
	// Style ID of the style applied to the paragraph; null if no style is applied
	StyleID string `json:"StyleID,omitempty"`
}
