/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Geolocation result
type GeolocateResponse struct {
	// Two-letter country code of IP address
	CountryCode string `json:"CountryCode,omitempty"`
	// Country name of IP address
	CountryName string `json:"CountryName,omitempty"`
	// City of IP address
	City string `json:"City,omitempty"`
	// State/region code of IP address
	RegionCode string `json:"RegionCode,omitempty"`
	// State/region of IP address
	RegionName string `json:"RegionName,omitempty"`
	// Zip or postal code of IP address
	ZipCode string `json:"ZipCode,omitempty"`
	// Timezone of IP address
	TimezoneStandardName string `json:"TimezoneStandardName,omitempty"`
	// Latitude of IP address
	Latitude float64 `json:"Latitude,omitempty"`
	// Longitude of IP address
	Longitude float64 `json:"Longitude,omitempty"`
}
