/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Instance of a form field that is handlebar style, such as \"{{FieldName}}\"
type HandlebarFormField struct {
	// Title of the handlebar style form field, such as \"FieldName\" in the case of \"{{FieldName}}\"
	FormFieldTitle string `json:"FormFieldTitle,omitempty"`
}
