/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Input array of documents to be processed for a merge operation
type DocumentArrayInput struct {
	// Array of document objects
	Documents []DocumentItem `json:"Documents,omitempty"`
}
