/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Request to replace a string in a string
type ReplaceStringSimpleRequest struct {
	// Input text content
	TextContent string `json:"TextContent,omitempty"`
	// Target input string to match and be replaced
	TargetString string `json:"TargetString,omitempty"`
	// Replacement for target string
	ReplaceWithString string `json:"ReplaceWithString,omitempty"`
}
