/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Result of detecting text encoding
type TextEncodingDetectResponse struct {
	// True if successful, false otherwise
	Successful bool `json:"Successful,omitempty"`
	// Text encoding used in file; possible values are ASCII, UTF7, UTF8, UTF16, BigEndianUnicode and UTF32
	TextEncoding string `json:"TextEncoding,omitempty"`
}
