/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Input to a Update Table Cell request
type UpdateDocxTableCellRequest struct {
	// Optional: Bytes of the input file to operate on
	InputFileBytes string `json:"InputFileBytes,omitempty"`
	// Optional: URL of a file to operate on as input.  This can be a public URL, or you can also use the begin-editing API to upload a document and pass in the secure URL result from that operation as the URL here (this URL is not public).
	InputFileUrl string `json:"InputFileUrl,omitempty"`
	// Table cell contents you would like to update the cell with
	CellToUpdate *DocxTableCell `json:"CellToUpdate,omitempty"`
	// 0-based index of the Table Row to update
	TableRowIndex int32 `json:"TableRowIndex,omitempty"`
	// 0-based index of the Table Cell (within the row) to update
	TableCellIndex int32 `json:"TableCellIndex,omitempty"`
	// Required; the path to the existing table to modify
	ExistingTablePath string `json:"ExistingTablePath,omitempty"`
}
