/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// EXIF tag and value
type ExifValue struct {
	// Tag name for the EXIF value
	Tag string `json:"Tag,omitempty"`
	// Date type of the EXIF value
	DataType string `json:"DataType,omitempty"`
	// Value, formatted as a string of the EXIF value
	DataValue string `json:"DataValue,omitempty"`
}
