/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveDocumentConvertApiClient

// Result of validating a URL with syntax only
type ValidateUrlResponseSyntaxOnly struct {
	// True if the URL is valid, false otherwise
	ValidURL bool `json:"ValidURL,omitempty"`
	// Well-formed version of the URL
	WellFormedURL string `json:"WellFormedURL,omitempty"`
}
