/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Result of performing a replace matching paragraphs operation on a Word Document
type ReplaceDocxParagraphResponse struct {
	// True if successful; false otherwise
	Successful bool `json:"Successful,omitempty"`
	// URL of the edited document
	EditedDocumentURL string `json:"EditedDocumentURL,omitempty"`
}
