/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Field definition and value in the form
type PdfFormField struct {
	// Name of the form field
	FieldName string `json:"FieldName,omitempty"`
	// The data type of the field; possible values are Text (FieldValue will be a string), Checkbox (FieldValue can be \"true\" or \"false\"), ComboBox (FieldComboBoxSelectedIndex will also be populated), Other
	FieldType string `json:"FieldType,omitempty"`
	// Value of the form field
	FieldValue string `json:"FieldValue,omitempty"`
	// Applies to ComboBox field types only; specifies the selected index of the combo box selection if available
	FieldComboBoxSelectedIndex int32 `json:"FieldComboBoxSelectedIndex,omitempty"`
}
