/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Row data to fill in to the DOCX Table
type DocxTableTableFillTableRow struct {
	// Cells in the row to fill in
	Cells []DocxTableTableFillTableCell `json:"Cells,omitempty"`
}
