/*
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package GoCloudmersiveDocumentConvertApiClient

// Result of getting comments hierarchically from a Word Document DOCX
type GetDocxCommentsHierarchicalResponse struct {
	// True if successful, false otherwise
	Successful bool `json:"Successful,omitempty"`
	// Comments in the document
	Comments []DocxTopLevelComment `json:"Comments,omitempty"`
	// The number of comments in the document
	TopLevelCommentCount int32 `json:"TopLevelCommentCount,omitempty"`
}
